name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Replace 'main' with your branch name if different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.13.1  # Use the Node.js version compatible with Slidev

      # Step 3: Install dependencies and build
      - name: Install and Build
        run: |
          npm i
          npm run build

      # Step 4: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist  # Slidev's default build output directory
